### ISSUE TITLE
builderscon tokyo 2016 サイトの文言

### ISSUE THREAD

**Issue by lestrrat** [builderscon/planning#16]
* 煽り文句
* ビジュアル
* ニュース的なもの
* 2, 3人いると良い

**Comment by richard-imaoka** [comment]
煽り文句7/19までにプルリク出します。

**Comment by richard-imaoka** [comment]
ちょっとニュースについて考えてみました。最初は以下のような運用でどうでしょう？

1. ニュース自体は.md (news.md?)にベタ書きで毎回追加
2. [builderscon.io](http://builderscon.io/)トップページにニュースセクションを追加、最新の5件のみとか
- [builderscon.io](http://builderscon.io/)Newsページに飛ぶと最新5件より多くニュースが見られる
3. [blog.builderscon.io](http://blog.builderscon.io/)の中で特に注目してもらいたいものは、都度、手動で[builderscon.io](http://builderscon.io/)のnews.md?に手で追加

3.に関して、例えばセッションタイマーのような重要なものはニュースとしてのせたい、月一スタッフミーティングはblogのみでよく、トップページのニュースに載せる必要なさそう？

**Comment by lestrrat** [comment]
これ、ここまで読んで、俺が「サイト」って書いている部分がすごく曖昧だったんだということに今更気づきました。まずタイトルを変えよう…

**Comment by lestrrat** [comment]
* さしあたって重要なのは conf.builderscon.io/tokyo/2016 なので、そちらの事を考える
* http://yapcasia.org/$year/ のそれぞれのページにあるような要素が必要、ということ。（他にもRubyKaigiでもPyConでもPHPConでも同じような事をしているはず）
* なお、将来的には builderscon.io は conf.builderscon.io で差し替えてもいいようなきはしてる…

**Comment by richard-imaoka** [comment]
ありがとうございます、明確になりました。ちょっとconfの方をよく見てIssueとしてAction Itemを上げようかな、とおもいます。
