### ISSUE TITLE
スタッフ用Slackを作る

### ISSUE THREAD

**Issue by lestrrat** [builderscon/planning#7]
* staff-bcon.slack.com ? staff-builderscon.slack.com ?
* 自動招待はしない
* 2回、3回と重ねるていくときに使い回す？使い回すならチャンネル名とかユーザー管理まわりを考える。
* お知らせ（Twitter等の投稿、カレンダー等からのリマインダ）を受け取るチャンネルを別途作る

**Comment by hasegawa-tomoki** [comment]
使い回すと、招待がラクな一方、何もしていない人が蓄積するので、棚卸しが必要ですね。
アーカイブとしてログを（無料で）残すことを考えると、毎年作るのがいいのかなあ…。
個人的には「Slackは完全にフローの情報なので、よく見る/重要な情報はストック的な場所（repo/wiki）に置いておく」が良いと思いますが、過去の経緯とかを追うのにフローが残ってると便利ではありますね。

**Comment by lestrrat** [comment]
slackの過去の情報、金払わないと検索性が著しく低いからなぁ
ログを残すならエクスポートしたものを取っておく、でもいいような気もする。
