### ISSUE TITLE
部屋スタッフ用のチートシートを作る

### ISSUE THREAD

**Issue by lestrrat** [builderscon/planning#8]
Google Driveに2，3ページの資料を作る

## 受付スタッフ

* 通常フロー
* 苦情係は誰か

## 部屋スタッフ

* セッション前にやるべき事
  * 録画進行の確認、必要があれば録画用マイク等の電池交換
  * スピーカー用マイクが複数ある場合は、前のセッションのものと交換、前のものは（そのようなタイプなら）充電へ。
  * スピーカーへの案内（10分前、5分前等のアナウンス）
  * 業務連絡があれば、まずそれをアナウンス
  * 「スピーカーが喜びますので、リアクションは3割増しで」
  * スピーカーの名前とセッションタイトルをアナウンス
* セッション中にやるべき事
  * セッションタイマー開始
  * 時間の確認、およびスピーカーへの通知
  * 60分トークの場合は40分にお知らせ1、45分にお知らせ2、50分にトーク終了、残りの10分はQ&A。スピーカーがどうしても終えられない場合、50分は超えても良いが、60分は死守
  * 30分トークの場合は20分にお知らせ、25分にトーク終了、残り5分はQ&A。
* セッション後にやるべき事
  * スタッフが率先して拍手
  * スピーカーに「○○さん、ありがとうございました」
  * 「もし他に質問等ありましたら、是非スピーカーの○○さんに後で直接ご質問ください」（任意）
  * 「ブログを是非書いて下さい」

**Comment by hasegawa-tomoki** [comment]
おお…ノウハウの塊だ。マイクの電池のことなんて1回やらかさないと思いつかないですね。

**Comment by hasegawa-tomoki** [comment]
どりゃ！（とりあえずすぐ手をつけた）

https://docs.google.com/document/d/1mmbLqn9r-DyeS1diT9aafWJQggGyB1q5iRTG2lWuDys/edit

**Comment by lestrrat** [comment]
ブラッシュアップは必要だけど、とりあえず使えるからこれはクローズしますね。
